#!/bin/bash
#
unset RUST_BACKTRACE
#workaround issue: 29293 https://github.com/rust-lang/rust/issues/29293


time cargo build -v && time ./`find -- target -maxdepth 2 -executable -not -type d`
# ./target/hello_world

