#!/bin/bash
#
#unset RUST_BACKTRACE
#workaround issue: 29293 https://github.com/rust-lang/rust/issues/29293

#echo $RUST_BACKTRACE

#workaround for set -e not playing nice with 'time' below, when exit codes are non-zero!
set +ev

#when compilation errors happen, none of the following 2 'time' will show any! apparently due to set -e  above!
( 
unset RUST_BACKTRACE
time cargo build -v
)
ec=$?
if test "$ec" -ne 0; then
  exit $ec
fi

#this won't be reached, when the above failed:
time ./`find -- target -maxdepth 2 -executable -not -type d`


#NEVERMIND: why not use cargo run ? you ask (it was my own fault for echo-ing to stdout, instead of stderr! via the ~/bin/rustc and cargo scripts), so the following doesn't apply! https://github.com/rust-lang/cargo/issues/2124
#
#     Running `target/debug/hello_world.so`
#Could not execute process `target/debug/hello_world.so` (never executed)
#
#Caused by:
#  No such file or directory (os error 2)
#

